/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Adriano
 */
public class BotoesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BotoesPanel
     */
    public BotoesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esquerdaButton = new javax.swing.JButton();
        cimaButton = new javax.swing.JButton();
        direitaButton = new javax.swing.JButton();
        baixoButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esquerdaButton.setText("←");
        esquerdaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esquerdaButtonActionPerformed(evt);
            }
        });
        esquerdaButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotoesPanel.this.keyPressed(evt);
            }
        });
        add(esquerdaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        cimaButton.setText("↑");
        cimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimaButtonActionPerformed(evt);
            }
        });
        cimaButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotoesPanel.this.keyPressed(evt);
            }
        });
        add(cimaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        direitaButton.setText("→");
        direitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direitaButtonActionPerformed(evt);
            }
        });
        direitaButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotoesPanel.this.keyPressed(evt);
            }
        });
        add(direitaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        baixoButton.setText("↓");
        baixoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixoButtonActionPerformed(evt);
            }
        });
        baixoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotoesPanel.this.keyPressed(evt);
            }
        });
        add(baixoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimaButtonActionPerformed
        Frame.sendSocket(87);
    }//GEN-LAST:event_cimaButtonActionPerformed

    private void direitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direitaButtonActionPerformed
        Frame.sendSocket(68);
    }//GEN-LAST:event_direitaButtonActionPerformed

    private void baixoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixoButtonActionPerformed
        Frame.sendSocket(83);
    }//GEN-LAST:event_baixoButtonActionPerformed

    private void esquerdaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esquerdaButtonActionPerformed
        Frame.sendSocket(65);
    }//GEN-LAST:event_esquerdaButtonActionPerformed

    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        Frame.sendSocket(evt.getKeyCode());
    }//GEN-LAST:event_keyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baixoButton;
    private javax.swing.JButton cimaButton;
    private javax.swing.JButton direitaButton;
    private javax.swing.JButton esquerdaButton;
    // End of variables declaration//GEN-END:variables
}
