/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Adriano
 */
public class BotoesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BotoesPanel
     */
    public BotoesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esquerdaButton = new javax.swing.JButton();
        cimaButton = new javax.swing.JButton();
        direitaButton = new javax.swing.JButton();
        baixoButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esquerdaButton.setText("←");
        esquerdaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esquerdaButtonActionPerformed(evt);
            }
        });
        add(esquerdaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        cimaButton.setText("↑");
        cimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimaButtonActionPerformed(evt);
            }
        });
        add(cimaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        direitaButton.setText("→");
        direitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direitaButtonActionPerformed(evt);
            }
        });
        add(direitaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        baixoButton.setText("↓");
        baixoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixoButtonActionPerformed(evt);
            }
        });
        add(baixoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimaButtonActionPerformed
        JOptionPane.showMessageDialog(cimaButton.getTopLevelAncestor(), "Movimento pra cima!", "Movimento!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cimaButtonActionPerformed

    private void direitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direitaButtonActionPerformed
        JOptionPane.showMessageDialog(direitaButton.getTopLevelAncestor(), "Movimento pra direita!", "Movimento!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_direitaButtonActionPerformed

    private void baixoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixoButtonActionPerformed
        JOptionPane.showMessageDialog(baixoButton.getTopLevelAncestor(), "Movimento pra trás!", "Movimento!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_baixoButtonActionPerformed

    private void esquerdaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esquerdaButtonActionPerformed
        JOptionPane.showMessageDialog(esquerdaButton.getTopLevelAncestor(), "Movimento pra esquerda!", "Movimento!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_esquerdaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baixoButton;
    private javax.swing.JButton cimaButton;
    private javax.swing.JButton direitaButton;
    private javax.swing.JButton esquerdaButton;
    // End of variables declaration//GEN-END:variables
}
