/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IGrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author Adriano
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputScrollPane = new javax.swing.JScrollPane();
        outputTextPane = new javax.swing.JTextPane();
        outputLabel = new javax.swing.JLabel();
        botoesPanel1 = new IGrafica.BotoesPanel();
        jPanel1 = new javax.swing.JPanel();
        camEsqueda = new javax.swing.JButton();
        camDireita = new javax.swing.JButton();
        lglImage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 650));

        outputTextPane.setEditable(false);
        outputTextPane.setMaximumSize(new java.awt.Dimension(0, 0));
        outputScrollPane.setViewportView(outputTextPane);

        outputLabel.setText("Output");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));

        camEsqueda.setText("←");
        camEsqueda.setToolTipText("");
        camEsqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camDireitaButton(evt);
            }
        });

        camDireita.setText("→");
        camDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camEsquedaButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(camEsqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camDireita)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camEsqueda)
                    .addComponent(camDireita))
                .addGap(42, 42, 42))
        );

        lglImage.setMaximumSize(new java.awt.Dimension(800, 600));
        lglImage.setMinimumSize(new java.awt.Dimension(640, 480));
        lglImage.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lglImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lglImage, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputScrollPane)
                    .addComponent(botoesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void camEsquedaButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camEsquedaButton
        Frame.sendSocket(39);
    }//GEN-LAST:event_camEsquedaButton

    private void camDireitaButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camDireitaButton
        Frame.sendSocket(37);
    }//GEN-LAST:event_camDireitaButton
    public void panelPrint(String msg) {
        Document doc = outputTextPane.getDocument();
        try {
            msg = msg + "\n";
            doc.insertString(doc.getLength(), msg, null);
        } catch (BadLocationException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JLabel getImgContainer() {
        return this.lglImage;
    }

    public void setImage(String name) {
        ImageIcon img = new ImageIcon("/home/lucas/" + name);
        lglImage.setIcon(img);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IGrafica.BotoesPanel botoesPanel1;
    private javax.swing.JButton camDireita;
    private javax.swing.JButton camEsqueda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lglImage;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextPane outputTextPane;
    // End of variables declaration//GEN-END:variables
}
